services:
    postgres:
        container_name: postgres_container
        image: postgres:17.6-alpine
        environment:
            POSTGRES_DB: "bookcrossing"
            POSTGRES_USER: "postgres"
            POSTGRES_PASSWORD: "123456"
        ports:
            - "6432:5432"
        healthcheck:
            test: ["CMD-SHELL", "pg_isready -U habrpguser -d habrdb"]
            interval: 10s
            timeout: 5s
            retries: 5
            start_period: 10s
        restart: unless-stopped
        deploy:
            resources:
                limits:
                    cpus: '1'
                    memory: 4G
        networks:
            - postgres

networks:
    postgres:
        driver: bridge
